  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0001.csv --clusters 2  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0002.csv --clusters 3  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0003.csv --clusters 4  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0004.csv --clusters 5  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0005.csv --clusters 6  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0006.csv --clusters 7  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0007.csv --clusters 8  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0008.csv --clusters 9  --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0009.csv --clusters 10 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0010.csv --clusters 11 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0011.csv --clusters 12 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0012.csv --clusters 13 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0013.csv --clusters 14 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0014.csv --clusters 15 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0015.csv --clusters 16 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0016.csv --clusters 17 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0017.csv --clusters 18 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0018.csv --clusters 19 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0019.csv --clusters 20 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0020.csv --clusters 21 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0021.csv --clusters 22 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0022.csv --clusters 23 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0023.csv --clusters 24 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0024.csv --clusters 25 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0025.csv --clusters 26 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0026.csv --clusters 27 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0027.csv --clusters 28 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0028.csv --clusters 29 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0029.csv --clusters 30 --max_iterations 500
  source VarEnv.sh ; mlpack_kmeans --seed ${seed0001} --input_file ${srcdir}/csv/dfmbio_num.csv --output_file ${srcdir}/csv/dfmbio_num_kmn0030.csv --clusters 31 --max_iterations 500
