  declare -gx strsrcdir="$HOME/mis.sources/contrib-src/R-3.6.1"

# R CMD SHLIB ${strsrcdir}/src/main/platform.c
# R CMD SHLIB ${strsrcdir}/src/main/version.c
# R CMD SHLIB ${strsrcdir}/src/main/complex.c
# R CMD SHLIB ${strsrcdir}/src/main/graphics.c
# R CMD SHLIB ${strsrcdir}/src/main/saveload.c
  R CMD SHLIB ${strsrcdir}/src/main/split-incl.c
# R CMD SHLIB ${strsrcdir}/src/main/envir.c
# R CMD SHLIB ${strsrcdir}/src/main/localecharset.c
# R CMD SHLIB ${strsrcdir}/src/main/gevents.c
# R CMD SHLIB ${strsrcdir}/src/main/print.c
# R CMD SHLIB ${strsrcdir}/src/main/bind.c
# R CMD SHLIB ${strsrcdir}/src/main/plot.c
# R CMD SHLIB ${strsrcdir}/src/main/raw.c
# R CMD SHLIB ${strsrcdir}/src/main/printutils.c
# R CMD SHLIB ${strsrcdir}/src/main/inspect.c
# R CMD SHLIB ${strsrcdir}/src/main/rlocale.c
  R CMD SHLIB ${strsrcdir}/src/main/qsort-body.c
# R CMD SHLIB ${strsrcdir}/src/main/deparse.c
# R CMD SHLIB ${strsrcdir}/src/main/radixsort.c
# R CMD SHLIB ${strsrcdir}/src/main/coerce.c
# R CMD SHLIB ${strsrcdir}/src/main/edit.c
# R CMD SHLIB ${strsrcdir}/src/main/cum.c
# R CMD SHLIB ${strsrcdir}/src/main/objects.c
# R CMD SHLIB ${strsrcdir}/src/main/plot3d.c
# R CMD SHLIB ${strsrcdir}/src/main/sort.c
# R CMD SHLIB ${strsrcdir}/src/main/array.c
# R CMD SHLIB ${strsrcdir}/src/main/sprintf.c
# R CMD SHLIB ${strsrcdir}/src/main/subset.c
# R CMD SHLIB ${strsrcdir}/src/main/dotcode.c
# R CMD SHLIB ${strsrcdir}/src/main/options.c
# R CMD SHLIB ${strsrcdir}/src/main/g_fontdb.c
# R CMD SHLIB ${strsrcdir}/src/main/strdup.c
# R CMD SHLIB ${strsrcdir}/src/main/seq.c
# R CMD SHLIB ${strsrcdir}/src/main/g_cntrlify.c
# R CMD SHLIB ${strsrcdir}/src/main/split.c
# R CMD SHLIB ${strsrcdir}/src/main/unique.c
# R CMD SHLIB ${strsrcdir}/src/main/g_alab_her.c
# R CMD SHLIB ${strsrcdir}/src/main/devices.c
# R CMD SHLIB ${strsrcdir}/src/main/format.c
# R CMD SHLIB ${strsrcdir}/src/main/dstruct.c
# R CMD SHLIB ${strsrcdir}/src/main/arithmetic.c
# R CMD SHLIB ${strsrcdir}/src/main/datetime.c
# R CMD SHLIB ${strsrcdir}/src/main/memory.c
# R CMD SHLIB ${strsrcdir}/src/main/alloca.c
# R CMD SHLIB ${strsrcdir}/src/main/connections.c
# R CMD SHLIB ${strsrcdir}/src/main/Renviron.c
# R CMD SHLIB ${strsrcdir}/src/main/internet.c
# R CMD SHLIB ${strsrcdir}/src/main/qsort.c
# R CMD SHLIB ${strsrcdir}/src/main/source.c
# R CMD SHLIB ${strsrcdir}/src/main/startup.c
# R CMD SHLIB ${strsrcdir}/src/main/apply.c
# R CMD SHLIB ${strsrcdir}/src/main/times.c
# R CMD SHLIB ${strsrcdir}/src/main/identical.c
# R CMD SHLIB ${strsrcdir}/src/main/debug.c
# R CMD SHLIB ${strsrcdir}/src/main/g_her_glyph.c
# R CMD SHLIB ${strsrcdir}/src/main/printvector.c
  R CMD SHLIB ${strsrcdir}/src/main/mkdtemp.c
# R CMD SHLIB ${strsrcdir}/src/main/builtin.c
# R CMD SHLIB ${strsrcdir}/src/main/gram-ex.c
# R CMD SHLIB ${strsrcdir}/src/main/summary.c
# R CMD SHLIB ${strsrcdir}/src/main/agrep.c
# R CMD SHLIB ${strsrcdir}/src/main/match.c
# R CMD SHLIB ${strsrcdir}/src/main/RNG.c
# R CMD SHLIB ${strsrcdir}/src/main/registration.c
# R CMD SHLIB ${strsrcdir}/src/main/strncasecmp.c
# R CMD SHLIB ${strsrcdir}/src/main/Rmain.c
# R CMD SHLIB ${strsrcdir}/src/main/lapack.c
# R CMD SHLIB ${strsrcdir}/src/main/subscript.c
# R CMD SHLIB ${strsrcdir}/src/main/altclasses.c
# R CMD SHLIB ${strsrcdir}/src/main/grep.c
# R CMD SHLIB ${strsrcdir}/src/main/sysutils.c
# R CMD SHLIB ${strsrcdir}/src/main/main.c
# R CMD SHLIB ${strsrcdir}/src/main/context.c
# R CMD SHLIB ${strsrcdir}/src/main/attrib.c
# R CMD SHLIB ${strsrcdir}/src/main/subassign.c
# R CMD SHLIB ${strsrcdir}/src/main/random.c
# R CMD SHLIB ${strsrcdir}/src/main/eval.c
# R CMD SHLIB ${strsrcdir}/src/main/duplicate.c
# R CMD SHLIB ${strsrcdir}/src/main/logic.c
# R CMD SHLIB ${strsrcdir}/src/main/plotmath.c
  R CMD SHLIB ${strsrcdir}/src/main/xspline.c
# R CMD SHLIB ${strsrcdir}/src/main/errors.c
# R CMD SHLIB ${strsrcdir}/src/main/scan.c
# R CMD SHLIB ${strsrcdir}/src/main/dounzip.c
# R CMD SHLIB ${strsrcdir}/src/main/list.c
# R CMD SHLIB ${strsrcdir}/src/main/character.c
# R CMD SHLIB ${strsrcdir}/src/main/paste.c
# R CMD SHLIB ${strsrcdir}/src/main/dcf.c
# R CMD SHLIB ${strsrcdir}/src/main/engine.c
# R CMD SHLIB ${strsrcdir}/src/main/altrep.c
# R CMD SHLIB ${strsrcdir}/src/main/CommandLineArgs.c
# R CMD SHLIB ${strsrcdir}/src/main/util.c
# R CMD SHLIB ${strsrcdir}/src/main/mapply.c
# R CMD SHLIB ${strsrcdir}/src/main/Rdynload.c
# R CMD SHLIB ${strsrcdir}/src/main/serialize.c
# R CMD SHLIB ${strsrcdir}/src/main/names.c
# R CMD SHLIB ${strsrcdir}/src/main/gram.c
# R CMD SHLIB ${strsrcdir}/src/main/printarray.c
# R CMD SHLIB ${strsrcdir}/src/main/colors.c
# R CMD SHLIB ${strsrcdir}/src/main/relop.c
# R CMD SHLIB ${strsrcdir}/src/main/iosupport.c
# R CMD SHLIB ${strsrcdir}/src/main/inlined.c

# libR\|mkdtemp\|qsort-body\|split-incl\|xspline
